//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.MSRC.Portal.CloudSecurity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class exceptionrequest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal exceptionrequest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.MSRC.Portal.CloudSecurity.Resources.exceptionrequest", typeof(exceptionrequest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string columnComments {
            get {
                return ResourceManager.GetString("columnComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact E-mail.
        /// </summary>
        internal static string columnContact {
            get {
                return ResourceManager.GetString("columnContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string columnStatus {
            get {
                return ResourceManager.GetString("columnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        internal static string columnSubmitted {
            get {
                return ResourceManager.GetString("columnSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription GUID.
        /// </summary>
        internal static string columnSubscriptionGuid {
            get {
                return ResourceManager.GetString("columnSubscriptionGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Number.
        /// </summary>
        internal static string columnTrackingNumber {
            get {
                return ResourceManager.GetString("columnTrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Azure Virtual Machines may receive exceptions.  Azure Web Apps, Logic Apps, and other non-VM deployments cannot receive exceptions..
        /// </summary>
        internal static string contentAssetType {
            get {
                return ResourceManager.GetString("contentAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending outbound e-mail to external domains (such as outlook.com, gmail.com, etc) directly from an e-mail server hosted in Azure compute services is not supported due to the elastic nature of public cloud service IPs and the potential for abuse.  As such, the Azure compute IP address blocks are added to public block lists (such as the Spamhaus PBL)..
        /// </summary>
        internal static string contentExceptionRequest1 {
            get {
                return ResourceManager.GetString("contentExceptionRequest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upon review, Microsoft may grant an exception to the e-mail policy.  This does not guarantee reliable e-mail delivery.  Hosting a mail server in Azure remains unsupported.  Azure Customer Service will be unable to troubleshoot e-mail delivery issues.  Uptime and SLA guarantees do not apply..
        /// </summary>
        internal static string contentExceptionRequest2 {
            get {
                return ResourceManager.GetString("contentExceptionRequest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An approved exception ensures that your IP addresses will be excluded from the opt-in blocklists that Microsoft Azure joins..
        /// </summary>
        internal static string contentExceptionRequest3 {
            get {
                return ResourceManager.GetString("contentExceptionRequest3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive a follow up in 2 business days..
        /// </summary>
        internal static string contentFollowUp {
            get {
                return ResourceManager.GetString("contentFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously Submitted Requests.
        /// </summary>
        internal static string contentHeadingPreviousRequest {
            get {
                return ResourceManager.GetString("contentHeadingPreviousRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Exception Request.
        /// </summary>
        internal static string contentHeadingRequest {
            get {
                return ResourceManager.GetString("contentHeadingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements for obtaining an Azure E-mail Policy Exception.
        /// </summary>
        internal static string contentHeadingRequirements {
            get {
                return ResourceManager.GetString("contentHeadingRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must configure a Static, Reserved, or Instance-level IP address.  The default dynamic IP addresses received by Azure Virtual Machines cannot be used for exceptions..
        /// </summary>
        internal static string contentIPType {
            get {
                return ResourceManager.GetString("contentIPType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previously submitted requests found.
        /// </summary>
        internal static string contentNoRequests {
            get {
                return ResourceManager.GetString("contentNoRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Agreements will receive immediate approval.
        /// </summary>
        internal static string contentRequirementAccountType1 {
            get {
                return ResourceManager.GetString("contentRequirementAccountType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Trial and MSDN subscriptions cannot receive exceptions.
        /// </summary>
        internal static string contentRequirementAccountType2 {
            get {
                return ResourceManager.GetString("contentRequirementAccountType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All other subscription types are subject to manual review by the security team.
        /// </summary>
        internal static string contentRequirementAccountType3 {
            get {
                return ResourceManager.GetString("contentRequirementAccountType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type:.
        /// </summary>
        internal static string contentRequirementHeading1 {
            get {
                return ResourceManager.GetString("contentRequirementHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type:.
        /// </summary>
        internal static string contentRequirementHeading2 {
            get {
                return ResourceManager.GetString("contentRequirementHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Type:.
        /// </summary>
        internal static string contentRequirementHeading3 {
            get {
                return ResourceManager.GetString("contentRequirementHeading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revocation:.
        /// </summary>
        internal static string contentRequirementHeading4 {
            get {
                return ResourceManager.GetString("contentRequirementHeading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception will be immediately revoked upon the following circumstances.
        /// </summary>
        internal static string contentRevocation {
            get {
                return ResourceManager.GetString("contentRevocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VM&apos;s IP address is changed (the Static IP address is removed).
        /// </summary>
        internal static string contentRevocation1 {
            get {
                return ResourceManager.GetString("contentRevocation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Security receives multiple complaints about SPAM or other abuse originating from this IP.
        /// </summary>
        internal static string contentRevocation2 {
            get {
                return ResourceManager.GetString("contentRevocation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Email Policy Exception Request.
        /// </summary>
        internal static string contentTitle {
            get {
                return ResourceManager.GetString("contentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your request.  Your tracking id is .
        /// </summary>
        internal static string contentTrackingNumber {
            get {
                return ResourceManager.GetString("contentTrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid page navigation attempted.
        /// </summary>
        internal static string invalidPageNavigationError {
            get {
                return ResourceManager.GetString("invalidPageNavigationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Comma separated).
        /// </summary>
        internal static string labelCommaSeparated {
            get {
                return ResourceManager.GetString("labelCommaSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact E-mail:.
        /// </summary>
        internal static string labelContactEmail {
            get {
                return ResourceManager.GetString("labelContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Volume:.
        /// </summary>
        internal static string labelExpectedVolume {
            get {
                return ResourceManager.GetString("labelExpectedVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Addresses:.
        /// </summary>
        internal static string labelIPAddresses {
            get {
                return ResourceManager.GetString("labelIPAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justification:.
        /// </summary>
        internal static string labelJustification {
            get {
                return ResourceManager.GetString("labelJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Messages per day).
        /// </summary>
        internal static string labelMessagesPerDay {
            get {
                return ResourceManager.GetString("labelMessagesPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string labelSubmit {
            get {
                return ResourceManager.GetString("labelSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription GUID:.
        /// </summary>
        internal static string labelSubscriptionGuid {
            get {
                return ResourceManager.GetString("labelSubscriptionGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-100.
        /// </summary>
        internal static string labelVolume1 {
            get {
                return ResourceManager.GetString("labelVolume1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100-1,000.
        /// </summary>
        internal static string labelVolume2 {
            get {
                return ResourceManager.GetString("labelVolume2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,000-100,000.
        /// </summary>
        internal static string labelVolume3 {
            get {
                return ResourceManager.GetString("labelVolume3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100,000+.
        /// </summary>
        internal static string labelVolume4 {
            get {
                return ResourceManager.GetString("labelVolume4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Text.
        /// </summary>
        internal static string placeholderText {
            get {
                return ResourceManager.GetString("placeholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security TechCenter.
        /// </summary>
        internal static string securityTechCenterBreadCrum {
            get {
                return ResourceManager.GetString("securityTechCenterBreadCrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Updates.
        /// </summary>
        internal static string securityUpdatesBreadCrum {
            get {
                return ResourceManager.GetString("securityUpdatesBreadCrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Security.
        /// </summary>
        internal static string securityUpdatesCloudSecurityBreadCrum {
            get {
                return ResourceManager.GetString("securityUpdatesCloudSecurityBreadCrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Email Hosting.
        /// </summary>
        internal static string securityUpdatesEmailHostingBreadCrum {
            get {
                return ResourceManager.GetString("securityUpdatesEmailHostingBreadCrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Policy Exception Request.
        /// </summary>
        internal static string securityUpdatesExceptionRequestBreadCrum {
            get {
                return ResourceManager.GetString("securityUpdatesExceptionRequestBreadCrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string statusApproved {
            get {
                return ResourceManager.GetString("statusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string statusPending {
            get {
                return ResourceManager.GetString("statusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string statusRejected {
            get {
                return ResourceManager.GetString("statusRejected", resourceCulture);
            }
        }
    }
}
