//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.MSRC.Portal.CloudSecurity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class policy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal policy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.MSRC.Portal.CloudSecurity.Resources.policy", typeof(policy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending outboud e-mail to external domains (such as outlook.com, gmail.com, etc) directly from and e-mail server hosted in Azure compute services is not supported due to the elastic nature of public cloud service IPs and the potential for abuse.  As such, the Azure compute IP address blocks are added to public block lists (such as the Spamhaus PBL)..
        /// </summary>
        internal static string contentAzureEmailHosting1 {
            get {
                return ResourceManager.GetString("contentAzureEmailHosting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This causes most e-mail providers to mark any mail sent via Azure-hosted servers as SPAM.  The only supported method for sending e-mail from Azure is to use another service outside Azure such as Exchange Online Protection, Sendgrid, or you own On-Prem e-mail server..
        /// </summary>
        internal static string contentAzureEmailHosting2 {
            get {
                return ResourceManager.GetString("contentAzureEmailHosting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have an e-mail server and occasionally need my Azure application to send e-mail.
        /// </summary>
        internal static string contentChoosing1 {
            get {
                return ResourceManager.GetString("contentChoosing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to host my organization&apos;s e-mail server in Azure.
        /// </summary>
        internal static string contentChoosing2 {
            get {
                return ResourceManager.GetString("contentChoosing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I send bulk e-mail or newsletters.
        /// </summary>
        internal static string contentChoosing3 {
            get {
                return ResourceManager.GetString("contentChoosing3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail relays will not work for my purposes.
        /// </summary>
        internal static string contentChoosing4 {
            get {
                return ResourceManager.GetString("contentChoosing4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring your application to send authenticated e-mail.
        /// </summary>
        internal static string contentChoosingLink1 {
            get {
                return ResourceManager.GetString("contentChoosingLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring your Azure Exchange server to use an Exchange Online Protection Smart Connector.
        /// </summary>
        internal static string contentChoosingLink2 {
            get {
                return ResourceManager.GetString("contentChoosingLink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring Sendgrid from your Azure application.
        /// </summary>
        internal static string contentChoosingLink3 {
            get {
                return ResourceManager.GetString("contentChoosingLink3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting an Azure E-mail Policy Exception.
        /// </summary>
        internal static string contentChoosingLink4 {
            get {
                return ResourceManager.GetString("contentChoosingLink4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See.
        /// </summary>
        internal static string contentChoosingSee {
            get {
                return ResourceManager.GetString("contentChoosingSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing the Right Method for You.
        /// </summary>
        internal static string contentHeadingChoosing {
            get {
                return ResourceManager.GetString("contentHeadingChoosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft&apos;s Commitment to Stop SPAM.
        /// </summary>
        internal static string contentHeadingStopSpam {
            get {
                return ResourceManager.GetString("contentHeadingStopSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malicious users of Azure who send SPAM e-mail negatively impact all customers.  &quot;IP Reputation&quot; is a concept used by the operators of many security appliances which dynamically block connections that are deemed risky.  SPAM e-mail is a significant data point used when computing IP reputation.  When an IP range gets dirtied by some evildoer, it can cause neighboring legitimate customers to be blocked..
        /// </summary>
        internal static string contentStopSpam {
            get {
                return ResourceManager.GetString("contentStopSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link 1.
        /// </summary>
        internal static string contentStopSpamLink1 {
            get {
                return ResourceManager.GetString("contentStopSpamLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link 2.
        /// </summary>
        internal static string contentStopSpamLink2 {
            get {
                return ResourceManager.GetString("contentStopSpamLink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Email Hosting.
        /// </summary>
        internal static string contentTitle {
            get {
                return ResourceManager.GetString("contentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security TechCenter.
        /// </summary>
        internal static string securityTechCenterBreadCrum {
            get {
                return ResourceManager.GetString("securityTechCenterBreadCrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Updates.
        /// </summary>
        internal static string securityUpdatesBreadCrum {
            get {
                return ResourceManager.GetString("securityUpdatesBreadCrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Security.
        /// </summary>
        internal static string securityUpdatesCloudSecurityBreadCrum {
            get {
                return ResourceManager.GetString("securityUpdatesCloudSecurityBreadCrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Email Hosting.
        /// </summary>
        internal static string securityUpdatesEmailHostingBreadCrum {
            get {
                return ResourceManager.GetString("securityUpdatesEmailHostingBreadCrum", resourceCulture);
            }
        }
    }
}
